### ISSUE TITLE
AFL-Fuzz Crash 000000:   parse.c:803 tmp is wild pointer

### ISSUE THREAD

**Issue by wcccccccc** [liyansong2018/elfspirit#3]
The stack information of crash is as follows：
![image](https://user-images.githubusercontent.com/41644934/159637818-ae9d578f-5204-40ea-9515-0ac4a1a2d2f5.png)
![image](https://user-images.githubusercontent.com/41644934/159637689-dd3b9580-4e80-40f4-8271-2c50d6385916.png)
![image](https://user-images.githubusercontent.com/41644934/159637912-2622f1b4-0214-469e-9610-999a98d52100.png)

**Comment by wcccccccc** [comment]
[crash1.zip](https://github.com/liyansong2018/elfspirit/files/8330458/crash1.zip)

**Comment by secnotes** [comment]
Stack
```
gef➤  bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7e555e8 in __vfprintf_internal (s=0x7ffff7fa76c0 <_IO_2_1_stdout_>, format=0x555555563f78 "     [%2d] %-15s 0x%-8x 0x%-8x 0x%-8x 0x%-6x 0x%-6x %-4s 0x%-5u\n", ap=ap@entry=0x7fffffffdd50, mode_flags=mode_flags@entry=0x0) at vfprintf-internal.c:1647
#2  0x00007ffff7e40a5b in __printf (format=<optimized out>) at printf.c:33
#3  0x0000555555560613 in display_segment64 (h=0x7fffffffdeb0) at parse.c:803
#4  0x000055555555edf6 in parse (elf=0x555555568420 <elf_name> "../crash1", po=0x5555555684a8 <po>) at parse.c:192
#5  0x0000555555558912 in readcmdline (argc=0x4, argv=0x7fffffffe0e8) at main.c:290
#6  0x0000555555558943 in main (argc=0x4, argv=0x7fffffffe0e8) at main.c:302
```

**Comment by liyansong2018** [comment]
Stack
```
gef➤  bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7e555e8 in __vfprintf_internal (s=0x7ffff7fa76c0 <_IO_2_1_stdout_>, format=0x555555563f78 "     [%2d] %-15s 0x%-8x 0x%-8x 0x%-8x 0x%-6x 0x%-6x %-4s 0x%-5u\n", ap=ap@entry=0x7fffffffdd50, mode_flags=mode_flags@entry=0x0) at vfprintf-internal.c:1647
#2  0x00007ffff7e40a5b in __printf (format=<optimized out>) at printf.c:33
#3  0x0000555555560613 in display_segment64 (h=0x7fffffffdeb0) at parse.c:803
#4  0x000055555555edf6 in parse (elf=0x555555568420 <elf_name> "../crash1", po=0x5555555684a8 <po>) at parse.c:192
#5  0x0000555555558912 in readcmdline (argc=0x4, argv=0x7fffffffe0e8) at main.c:290
#6  0x0000555555558943 in main (argc=0x4, argv=0x7fffffffe0e8) at main.c:302
```
